# Generated by Django 5.0.4 on 2024-05-30 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SharedNote',
            fields=[
                ('id_shared', models.AutoField(primary_key=True, serialize=False)),
                ('shared_at', models.DateTimeField(auto_now=True)),
                ('permission_type', models.CharField(max_length=50)),
                ('id_note', models.ForeignKey(db_column='id_note', on_delete=django.db.models.deletion.CASCADE, to='api.note')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'shared_notes',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='sharednote',
            index=models.Index(fields=['id_user'], name='shared_note_id_user_899d26_idx'),
        ),
        migrations.AddIndex(
            model_name='sharednote',
            index=models.Index(fields=['id_note'], name='shared_note_id_note_0f62f4_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['id_user'], name='notes_id_user_528715_idx'),
        ),
    ]
