# Generated by Django 5.0.4 on 2024-06-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharednote',
            name='permission_type',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=50),
        ),
    ]
